name: SchoolWars
version: '${project.version}'
main: de.kuscheltiermafia.schoolwars.SchoolWars
api-version: '1.21'
commands:
  start:
    description: Starts the game
  clearTeams:
    description: clears all teams
  itemlist:
    description: opens a list with all items
  teamlist:
    description: lists all players in the teams
  debug:
    description: Debug commands
